[workspace]
members = ["examples/positron/frontend/src-tauri"]

[package]
name = "tauri-plugin-passkey"
version = "0.1.0"
authors = ["You"]
description = ""
edition = "2021"
rust-version = "1.81"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-passkey"

[dependencies]
tauri = { version = "2.5.0" }
serde = "1.0"
thiserror = "2"
webauthn-authenticator-rs = { version = "0.5.0", features = [
  "nfc",
  "usb",
], optional = true }
webauthn-rs-proto = { version = "0.5.0", optional = true }
futures = { version = "0.3.31", optional = true }
log = { version = "0.4.27", optional = true }

[build-dependencies]
tauri-plugin = { version = "2.2.0", features = ["build"] }

[features]
default = ["desktop", "log"]
mobile = []
desktop = [
  "dep:webauthn-authenticator-rs",
  "dep:webauthn-rs-proto",
  "dep:futures",
]
log = ["dep:log"]
