name: Checks and Validation
on:
  pull_request_target:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    environment: ${{ github.event.pull_request.head.repo.full_name == github.repository && 'internal-ci' || 'external-ci' }}
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # latest
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev libpcsclite-dev
          version: 1.1

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "linter_cache"
          save-if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      - uses: bahmutov/npm-install@v1
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          useLockFile: false

      - name: Run linters
        uses: profiidev/rust-lint-action@ec3bf81f84ae2a9834fce8967d0eabe852227ff9 # v4
        with:
          auto_fix: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
          rustfmt: true
          clippy: true
          clippy_args: "--all-targets"
          prettier: true
          prettier_extensions: "css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml,svelte"
          oxlint: true
          git_sign_commits: true
          github_token: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
