name: Checks and Validation
on:
  pull_request_target:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    environment: ${{ github.event.pull_request.head.repo.full_name == github.repository && 'internal-ci' || 'external-ci' }}
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable

      - name: refresh apt index (ubuntu only)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: sudo apt-get update

      - uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # latest
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev libpcsclite-dev
          version: 1.2

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          cache-on-failure: true
          shared-key: "linter_cache"
          save-if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      - uses: bahmutov/npm-install@v1
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          useLockFile: false

      - name: Run linters
        uses: profiidev/rust-lint-action@6592fe2b81f52c155bc416c51b6a860196a96f48 # v4
        with:
          auto_fix: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
          rustfmt: true
          clippy: true
          clippy_args: "--all-targets"
          prettier: true
          prettier_extensions: "css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml,svelte"
          oxlint: true
          git_sign_commits: true
          github_token: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
