on:
  push:
    branches:
      - main

name: release-please

permissions:
  contents: read
  id-token: write

jobs:
  release-plz:
    name: Release-plz
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev libpcsclite-dev
          version: 1.1

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "release"

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - uses: bahmutov/npm-install@v1
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          useLockFile: false
      - run: npm publish --provenance --access public
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        env:
          NODE_AUTH_TOKEN: ""
