on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev libpcsclite-dev
          version: 1.1

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "release"

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - uses: bahmutov/npm-install@v1
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          useLockFile: false
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.releases_created == 'true' }}
