on:
  push:
    branches:
      - main

name: release-please

permissions:
  contents: read
  id-token: write

jobs:
  release-plz:
    name: Release-plz
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable

      - name: refresh apt index (ubuntu only)
        run: sudo apt-get update

      - uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # latest
        with:
          packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev libpcsclite-dev
          version: 1.2

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "release"

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - uses: bahmutov/npm-install@v1
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          useLockFile: false
      - run: npm publish --provenance --access public
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        env:
          NODE_AUTH_TOKEN: ""
