on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "release"

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

      - uses: bahmutov/npm-install@v1
        if: ${{ steps.release.outputs.releases_created }}
        with:
          useLockFile: false
      - run: npm run build
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}
